### ISSUE TITLE
Handling illegal Okada models

### ISSUE THREAD

**Issue by mchristoffersen** [uafgeotools/vmod#6]
The function vmod.source.okada.model_gen returns a length three list of lists of nans when given some kinds of invalid inputs (see lines 185-197 in okada.py). When model_gen is used to calculate tilt this behavior will cause an error in vmod.data.tilt.from_model3d which is expecting a length two list to be returned. 

Code to replicate:
```
import numpy as np

import vmod.source
import vmod.data

# Initialize data
tiltm = vmod.data.tilt.Tilt()

tiltm.add_xs(np.array([-100]))
tiltm.add_ys(np.array([100]))
tiltm.add_dx(np.array([1e-6]))
tiltm.add_dy(np.array([1e-6]))

tiltm.add_err(np.array([1e-7]), np.array([1e-7]))

# Ask for an illegal (width=-1) okada model
okad = vmod.source.okada.Okada(tiltm)
okad.set_type("open")

# xcen, ycen, depth, length, width, opening, strike, dip
x = [0, 0, 100, 10, -1, 1, 0, 90]

okad.forward(x)
```

Error:
```
Traceback (most recent call last):
  File "/home/mchristo/proj/ms/vmod/msc/tilt_error.py", line 23, in <module>
    okad.forward(x)
  File "/home/mchristo/proj/ms/vmod/vmod/source/source.py", line 285, in forward
    answer = self.data.from_model(func_tilt,offsets,unravel)
  File "/home/mchristo/proj/ms/vmod/vmod/data/data.py", line 470, in from_model
    model=self.from_model3d(func)
  File "/home/mchristo/proj/ms/vmod/vmod/data/tilt.py", line 130, in from_model3d
    dx,dy=func(self.xs,self.ys)
ValueError: too many values to unpack (expected 2)
```

This is an issue for for the inverse routines which automatically explore the parameter space and may give model_gen illegal inputs. Would it be better to raise a ValueError for all illegal inputs to model_gen and have the calling function handle that?

**Comment by mfangaritav** [comment]
The bug has been fixed in a547291
